import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

// importing custom components
import Header from '../components/Home/Header'
import ValueProposition from '../components/Home/ValueProposition'

const Home: NextPage = () => {
  const {status}=useSession()
  if(status === "authenticated")
  window.location.replace(`${window.location.origin}/dashboard`)
  return (
    <div className="bg-primaryBg">
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ValueProposition />
    </div>
  ) 
}

export default Home
