import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'

import Head from 'next/head'

// importing custom components
import Header from '../components/Home/Header'
import ValueProposition from '../components/Home/ValueProposition'

const Home: NextPage = () => {
  const router = useRouter()
  const { status } = useSession()

  if (status === "authenticated")
    router.push('/dashboard')

  return (
    <div className="bg-primaryBg dark:bg-primaryBgDark">
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ValueProposition />
    </div>
  )
}

export default Home
